name: CI

on: [push, pull_request]

jobs:
  tests:
    name: "Run tests on PHP ${{ matrix.php-version }}"
    if: "!contains(github.event.head_commit.message, 'WIP')"

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        php-version: [ 8.0 ]
        experimental: [ false ]

    environment: test

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: xdebug
          coverage: xdebug
          tools: phive, composer:v2
      - name: "Cache Composer dependencies"
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: "Install Composer dependencies"
        uses: php-actions/composer@v6
        with:
          php_version: 8.0
          dev: yes
          args: --no-interaction --no-progress --no-suggest --optimize-autoloader
      - name: "PHPStan Static Analysis"
        run: vendor/bin/phpstan analyse src --level 8